#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                  # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           :                                          # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://bitcoin-brainbow.github.io/app-landing-page/1                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://bitcoin-brainbow.github.io/app-landing-page/2                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : https://avatars.githubusercontent.com/u/113306748?s=400&u=01faa6cebb6d915009ca43474eb7b9ff909e2274&v=4 # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Brainbow Wallet                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free, Donation                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : After the storm, no matter where you go, you will find your pot of digital gold (bitcoin) at the end of the Brainbow.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Team Brainbow                                
your_link                                 :                       
your_city                                 :                                  
email_address                             :  
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : bitcoinbrainbow
github_username                           : Bitcoin-Brainbow
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Login-to-Bitcoin approach
    description                           : Instead of using 12/24 recovery words nobody can't remember, Brainbow Wallet uses the WarpWallet technique to generate your HD Wallet. 
    fontawesome_icon_name                 : tor
    
  - title                                 : RBF
    description                           : Replace by Fee support, on by default
    fontawesome_icon_name                 : plus

  - title                                 : Tor 
    description                           : Preview app video on the iPhone device simply by placing your video files in the videos folder.
    fontawesome_icon_name                 : play-circle

  - title                                 : Automatic Icon and Metadata
    description                           : Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
    fontawesome_icon_name                 : sync

  - title                                 : Live exchange rates
    description                           : Live exchange rates between BTC/Sats and fiat currencies.
    fontawesome_icon_name                 : exchange
  
  - title                                 : Stateless mobile wallet 
    description                           : Nothing is stored on the device. Log-of, and everything is removed automagically. Use someone else's mobile to access your bitcoin.
    fontawesome_icon_name                 : star

  - title                                 : Easy wallet-to-wallet transfer
    description                           : Migrate or clone wallet using standard wallet import format (WIF) or BIP39 mnemonic seed words. 
    fontawesome_icon_name                 : sync

  - title                                 : Social Links
    description                           : 
    fontawesome_icon_name                 : link

  - title                                 : FontAwesome Support
    description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : info-circle

  - title                                 : FontAwesome Support
    description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : info-circle
    
  - title                                 : FontAwesome Support
    description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : info-circle
    
  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    #
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000000"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#000000"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
